import importlib

printerlist = {
    'pretore': ('Pretore', 'l_pr_pretore')
}

def init_printers(view):
    res = {}
    for k, v in printerlist.items():
        module = importlib.import_module("ptxprint.printers."+k)
        c = getattr(module, v[0])
        res[k] = c(view)
    return res

def printer_from_label(lid):
    for k, v in printerlist.items():
        if v[1] == lid:
            return k
    return None

allcurrencies = {
    "AFN":  "؋",
    "AMD":  "֏",
    "AOA":  "Kz",
    "ARS":  "$",
    "AUD":  "A$",
    "AZN":  "₼",
    "BAM":  "KM",
    "BBD":  "$",
    "BDT":  "৳",
    "BMD":  "$",
    "BND":  "$",
    "BOB":  "Bs",
    "BRL":  "R$",
    "BSD":  "$",
    "BWP":  "P",
    "BZD":  "$",
    "CAD":  "CA$",
    "CLP":  "$",
    "CNY":  "CN¥",
    "COP":  "$",
    "CRC":  "₡",
    "CUC":  "$",
    "CUP":  "$",
    "CZK":  "Kč",
    "DKK":  "kr",
    "DOP":  "$",
    "EGP":  "E£",
    "ESP":  "₧",
    "EUR":  "€",
    "FJD":  "$",
    "FKP":  "£",
    "GBP":  "£",
    "GEL":  "₾",
    "GHS":  "GH₵",
    "GIP":  "£",
    "GNF":  "FG",
    "GTQ":  "Q",
    "GYD":  "$",
    "HKD":  "HK$",
    "HNL":  "L",
    "HRK":  "kn",
    "HUF":  "Ft",
    "IDR":  "Rp",
    "ILS":  "₪",
    "INR":  "₹",
    "ISK":  "kr",
    "JMD":  "$",
    "JPY":  "JP¥",
    "KGS":  "⃀",
    "KHR":  "៛",
    "KMF":  "CF",
    "KPW":  "₩",
    "KRW":  "₩",
    "KYD":  "$",
    "KZT":  "₸",
    "LAK":  "₭",
    "LBP":  "L£",
    "LKR":  "Rs",
    "LRD":  "$",
    "LTL":  "Lt",
    "LVL":  "Ls",
    "MGA":  "Ar",
    "MMK":  "K",
    "MNT":  "₮",
    "MUR":  "Rs",
    "MXN":  "MX$",
    "MYR":  "RM",
    "NAD":  "$",
    "NGN":  "₦",
    "NIO":  "C$",
    "NOK":  "kr",
    "NPR":  "Rs",
    "NZD":  "NZ$",
    "PHP":  "₱",
    "PKR":  "Rs",
    "PLN":  "zł",
    "PYG":  "₲",
    "RON":  "lei",
    "RUB":  "₽",
    "RWF":  "RF",
    "SAR":  "⃁",
    "SBD":  "$",
    "SEK":  "kr",
    "SGD":  "$",
    "SHP":  "£",
    "SRD":  "$",
    "SSP":  "£",
    "STN":  "Db",
    "SYP":  "£",
    "THB":  "฿",
    "TOP":  "T$",
    "TRY":  "₺",
    "TTD":  "$",
    "TWD":  "NT$",
    "UAH":  "₴",
    "USD":  "US$",
    "UYU":  "$",
    "VEF":  "Bs",
    "VND":  "₫",
    "XAF":  "FCFA",
    "XCD":  "EC$",
    "XCG":  "Cg.",
    "XOF":  "F CFA",
    "XPF":  "CFPF",
    "XXX":  "¤",
    "ZAR":  "R",
    "ZMW":  "ZK",
}
