#!/usr/bin/python3

import argparse, zipfile, os
from ptxprint.utils import bookcodes

ptxfiles = ["BookNames.xml", "Settings.xml", "hyphenatedWords.txt", "en.ldml"]

parser = argparse.ArgumentParser()
parser.add_argument("-b","--bsbdir",required=True,help="Directory containing BSB source usfm files")
parser.add_argument("-p","--ptxdir",required=True,help="Paratext project dir for other stuff")
parser.add_argument("-o","--outfile",required=True,help="Generated zip file")
args = parser.parse_args()

with zipfile.ZipFile(args.outfile, "w", compression=zipfile.ZIP_BZIP2) as outz:
    for k, v in bookcodes.items():
        infile = os.path.join(args.bsbdir, k+".usfm")
        if not os.path.exists(infile):
            continue
        outfile = "{}{}BSB.usfm".format(v, k)
        outz.write(infile, outfile)
    for k in ptxfiles:
        infile = os.path.join(args.ptxdir, k)
        if os.path.exists(infile):
            outz.write(infile, k)

