#!/usr/bin/python3

import argparse, sys, os, re, configparser, subprocess, platform
import site, logging
from shutil import rmtree
from zipfile import ZipFile

if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    site.USER_BASE = os.path.join(os.path.expanduser("~"), ".local")
    if not hasattr(site, 'getuserbase'):
        site.getuserbase = lambda : site.USER_BASE
    os.putenv("PATH", sys._MEIPASS)

try:
    import ptxprint
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(__file__), "..", "lib"))
    import ptxprint
from ptxprint.utils import saferelpath
from ptxprint.pdf.pdfsig import make_signatures, get_page_size
from ptxprint.pdf.pdfdiff import createDiff
from ptxprint.pdf.procpdf import procpdf

from pathlib import Path
import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
gi.require_version('Poppler', '0.18')
from gi.repository import Gtk
from ptxprint.gtkutils import getWidgetVal, setWidgetVal, setFontButton, makeSpinButton, doError
from ptxprint.utils import pycodedir

def getnsetlang(config):
    envlang = os.getenv("LANG", None)
    oldlang = config.get("init", "syslang", fallback=None)
    newlang = config.get("init", "lang", fallback=None)
    if envlang is None or oldlang == envlang:
        return newlang
    config.set("init", "lang", envlang or "")
    config.set("init", "syslang", envlang or "")
    return envlang

def get_sheet_size(sheet_text):
    sheet_sizes = {
        "420mm, 594mm (A2)": "a2",
        "297mm, 420mm (A3)": "a3",
        "210mm, 297mm (A4)": "a4",
        "17in, 22in (ANSI C)": "431.8x558.8",
        "11in, 17in (ANSI B)": "279.4x431.8",
        "8.5in, 11in (Letter)": "ltr",
        "353mm, 500mm (B3)": "353x500",
        "250mm, 353mm (B4)": "250x353",
        "176mm, 250mm (B5)": "176x250",
    }
    if sheet_text in sheet_sizes:
        return sheet_sizes[sheet_text]
    if sheet_text.count(',') != 1:
        raise IOError('Format of sheet dimensions not understood. Please specify in format "width, height"')
    width, height = sheet_text.split(',')
    if 'mm' in width:
        width = float(width.split('mm')[0])
    elif 'in' in width:
        width = float(width.split('in')[0]) * 25.4
    else:
        raise IOError('Unknown or unspecified unit!')
    if 'mm' in height:
        height = float(height.split('mm')[0])
    elif 'in' in height:
        height = float(height.split('in')[0]) * 25.4
    else:
        raise IOError('Unknown or unspecified unit!')
    return 'x'.join((str(width), str(height)))

class Finisher(Gtk.Application):
    def __init__(self):
        super().__init__()
        self.builder = Gtk.Builder()
        gladefile = os.path.join(pycodedir(), "pdfinish.glade")
        self.builder.add_from_file(gladefile)
        self.builder.connect_signals(self)
        self.mw = self.builder.get_object("pdfinish")

        self.mw.show_all()
        Gtk.main()

    def onProcessClicked(self, btn):
        self.input_pdf_path = self.builder.get_object("fp_input").get_filename()
        if not self.input_pdf_path:
            raise IOError("You need to select an input file!")
        dialog = Gtk.FileChooserDialog(
            title="Select output file",
            parent=self.mw,
            action=Gtk.FileChooserAction.SAVE,
        )
        dialog.add_buttons(
                Gtk.STOCK_CANCEL, Gtk.ResponseType.CANCEL,
                Gtk.STOCK_SAVE, Gtk.ResponseType.OK
        )

        dialog.set_do_overwrite_confirmation(True)
        response = dialog.run()

        if response == Gtk.ResponseType.OK:
            self.output_filepath = dialog.get_filename()
            print("Selected file:", self.output_filepath)
        dialog.destroy()
        if response != Gtk.ResponseType.OK:
            return

        notebook = self.builder.get_object('pdfinish_notebook')
        current_page_id = notebook.get_current_page()

        if current_page_id == 0:
            self._run_pdfdiff()
        elif current_page_id == 1:
            self._run_pdfsig()
        elif current_page_id == 2:
            self._run_procpdf()
        elif current_page_id == 3:
            self._run_overlay()
        elif current_page_id == 4:
            self._run_watermark()
        else:
            raise Exception("Unknown page id")

        if not os.path.exists(self.output_filepath):
            raise Exception("File not created as expected!")
        # open output PDF
        if platform.system() == 'Darwin':       # macOS
            subprocess.call(('open', self.output_filepath))
        elif platform.system() == 'Windows':    # Windows
            os.startfile(self.output_filepath)
        else:                                   # linux variants
            subprocess.call(('xdg-open', self.output_filepath))
        pass

    def onCloseClicked(self, btn):
        Gtk.main_quit()

    def onDestroy(self, btn):
        Gtk.main_quit()

    def _run_pdfdiff(self):
        """
        Run pdfdiff from Gtk application
        """
        base_pdf_path = self.builder.get_object("fp_compare").get_filename()
        input_diff_rgba = self.builder.get_object("col_ndiffColor").get_rgba()
        input_diff_color = (input_diff_rgba.red * 256, input_diff_rgba.green  * 256, input_diff_rgba.blue  * 256)
        base_diff_rgba = self.builder.get_object("col_odiffColor").get_rgba()
        base_diff_color = (base_diff_rgba.red * 256, base_diff_rgba.green  * 256, base_diff_rgba.blue  * 256)
        # 'Offset starting page' option - what it is?
        onlydiffs = self.builder.get_object("c_onlyDiffs").get_active()
        diffpages = int(self.builder.get_object("s_diffpages").get_value())

        if not base_pdf_path:
            raise IOError("You need to select a file for computing the diff!")
        createDiff(self.input_pdf_path, base_pdf_path, self.output_filepath, doError, color=input_diff_color,
                                onlydiffs=onlydiffs, oldcolor=base_diff_color, limit=diffpages)

    def _run_pdfsig(self):
        """
        Run pdfsig from Gtk application
        """
        pages_per_spread = self.builder.get_object("ecb_pagesPerSpread").get_active_id()
        sheets_per_sig = int(self.builder.get_object("s_sheetsPerSignature").get_value())
        fold_cut_margin = self.builder.get_object("s_foldCutMargin").get_value()
        add_crop_marks = self.builder.get_object("c_cropmarks").get_active()
        right_to_left = self.builder.get_object("c_RTL").get_active()
        fold_first = self.builder.get_object("c_foldFirst").get_active()
        sheetsize_active_text = self.builder.get_object("ecb_sheetSize").get_active_text()
        selected_sheet_size = get_sheet_size(sheetsize_active_text)
        outwidth, outheight = get_page_size(selected_sheet_size)
        make_signatures(self.input_pdf_path, outwidth, outheight, pages_per_spread,
                        sheets_per_sig, fold_cut_margin, add_crop_marks, right_to_left, fold_first, outfname=self.output_filepath)

    def _run_procpdf(self):
        """
        Run formatting from Gtk application
        """
        output_format = self.builder.get_object("ecb_outputFormat").get_active_id()  # aka, ispdfxa
        spot_rgba = self.builder.get_object("col_spotColor").get_rgba()
        spottolerance = self.builder.get_object("s_spotColorTolerance").get_value()
        spotcolor = f"rgb({spot_rgba.red * 256}, {spot_rgba.green  * 256}, {spot_rgba.blue  * 256})"

        # run procpdf - what does outfname do?
        procpdf(self.output_filepath, self.input_pdf_path, output_format, doError, None, cover=None, spottolerance=spottolerance, spotcolor=spotcolor, output_filepath=self.output_filepath)

    def _run_overlay(self):
        """
        Run overlaying from Gtk application
        """
        raise NotImplementedError

    def _run_watermark(self):
        """
        Run watermarking from Gtk application
        """
        raise NotImplementedError


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("infile",nargs="?",help="Input PDF file")

    if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
        from ptxprint.gtkutils import HelpTextViewWindow
        tv = HelpTextViewWindow()
        def print_message(message, file=None):
            tv.print_message(message)
        parser._print_message = print_message

    args = parser.parse_args()

    finisher = Finisher()

if __name__=="__main__": main()
