#!/usr/bin/python3

import sys, site, os

if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    site.USER_BASE = os.path.join(os.path.expanduser("~"), ".local")
    if not hasattr(site, 'getuserbase'):
        site.getuserbase = lambda : site.USER_BASE
    os.putenv("PATH", sys._MEIPASS)

try:
    from ptxprint.main import main
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(__file__), "..", "lib"))
    from ptxprint.main import main

if __name__ == "__main__":
    main()
