#!/usr/bin/env python3

import os, argparse, re, regex
from ptxprint.utils import runChanges
from ptxprint.changes import readChanges

import logging

logger = logging.getLogger(__name__)

parser = argparse.ArgumentParser()
parser.add_argument("infile",help="Input file")
parser.add_argument("-o","--outfile",help="Output file")
parser.add_argument("-c","--changes",help="changes.txt")
parser.add_argument("-s","--section",action='append',default=[],help="Sections to run in order")
parser.add_argument('-b','--book',help='Book code')
args = parser.parse_args()

changes = readChanges(args.changes, args.book)
with open(args.infile, encoding="utf-8") as inf:
    dat = inf.read()

if not len(args.section):
    args.section = ["default"]

for s in args.section:
    c = changes.get(s, None)
    if c is None:
        continue
    dat = runChanges(c, args.book, dat)

if args.outfile:
    with open(args.outfile, "w", encoding="utf-8") as outf:
        outf.write(dat)



