#!/usr/bin/python3

import sys, os, argparse
try:
    from ptxprint.usfmerge import usfmerge
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(__file__), "..", "lib"))
    from ptxprint.usfmerge import usfmerge

parser = argparse.ArgumentParser()
parser.add_argument("infilea", help="Main input file")
parser.add_argument("infileb", help="Secondary input file")
parser.add_argument("-o","--outfile",help="output file")
parser.add_argument("-a","--astylesheet",default=[],action="append",help="add another stylesheet for infilea")
parser.add_argument("-b","--bstylesheet",default=[],action="append",help="add another stylesheet for infileb")
parser.add_argument("-s","--stylesheet",default=[],action="append",help="add another stylesheet for both files")
parser.add_argument("--fsecondary",action="store_true",help="Use fig elements from secondary not primary source")
parser.add_argument("--debug",action="store_true",help="Print out debug statements")
args = parser.parse_args()

sheetsa = args.stylesheet + args.astylesheet
sheetsb = args.stylesheet + args.bstylesheet
usfmerge(args.infilea, args.infileb, args.outfile, stylesheetsa=sheetsa, stylesheetsb=sheetsb, fsecondary=args.fsecondary, debug=args.debug)
